import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Suspense>{children}</Suspense>
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#1e003e",
              color: "#f3e8ff",
              border: "1px solid #7f3fbf",
              padding: "12px 16px",
              fontSize: "14px",
            },
            success: {
              iconTheme: {
                primary: "#a855f7",
                secondary: "#f3e8ff",
              },
            },
            error: {
              iconTheme: {
                primary: "#f43f5e",
                secondary: "#f3e8ff",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
